server:
    port: 9090

spring:
    datasource:
        url: jdbc:mysql://120.77.203.216/gyt?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
#        url: jdbc:mysql://localhost/test3?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456


    thymeleaf:
        mode: LEGACYHTML5
# 取消模板文件缓存
        cache: false

#    #设定thymeleaf文件路径 默认为src/main/resources/templates
#    freemarker:
#        template-loader-path: classpath:/templates

#    #设定静态文件路径，js,css等
#    mvc:
#        static-path-pattern: /static/**

    servlet:
        multipart:
        # 设置单个文件大小
            max-file-size: 200MB
        # 设置单次请求文件的总大小
            max-request-size: 200MB

#mybatis-plus:
mybatis:
    type-aliases-package: com.example.demo.bean
#    mapper-locations: classpath*:/mapper/*Mapper.xml
    mapper-locations: classpath*:/mapper/*.xml
#    configuration:
        # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
#        map-underscore-to-camel-case: true

#showSql
logging:
    level:
        com:
            example:
                mapper: debug
